In [33]:
#1. Import the NUMPY package under the name np.
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [34]:
#2. Print the NUMPY version and the configuration.
np.version.version


'1.21.5'

In [168]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a= np.random.random(((2,3,5)))


In [169]:
#4. Print a.

a

array([[[0.67474401, 0.34385214, 0.18143654, 0.65733041, 0.72172414],
        [0.3038035 , 0.9088724 , 0.41034944, 0.84218253, 0.11612205],
        [0.6405535 , 0.8426777 , 0.8843958 , 0.21406958, 0.72561716]],

       [[0.82501907, 0.07317282, 0.72109159, 0.99858954, 0.89507733],
        [0.66160792, 0.73295926, 0.37149319, 0.23335855, 0.7405161 ],
        [0.67890123, 0.86729561, 0.93640664, 0.45413795, 0.1224886 ]]])

In [170]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b= np.ones(((5,2,3)))

In [171]:
#6. Print b

b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [172]:
#7. Do a and b have the same size? How do you prove that in Python code

a.size == b.size

True

In [173]:
#8. Are you able to add a and b? Why or why not?

a+b
# No porque no coincide el numero de filas de b con columnas de a

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [174]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c= b.transpose(1,2,0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [175]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d= a+c
d

array([[[1.67474401, 1.34385214, 1.18143654, 1.65733041, 1.72172414],
        [1.3038035 , 1.9088724 , 1.41034944, 1.84218253, 1.11612205],
        [1.6405535 , 1.8426777 , 1.8843958 , 1.21406958, 1.72561716]],

       [[1.82501907, 1.07317282, 1.72109159, 1.99858954, 1.89507733],
        [1.66160792, 1.73295926, 1.37149319, 1.23335855, 1.7405161 ],
        [1.67890123, 1.86729561, 1.93640664, 1.45413795, 1.1224886 ]]])

In [176]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print('    ')
print(d)

# d es un orden de magnitud mayor


[[[0.67474401 0.34385214 0.18143654 0.65733041 0.72172414]
  [0.3038035  0.9088724  0.41034944 0.84218253 0.11612205]
  [0.6405535  0.8426777  0.8843958  0.21406958 0.72561716]]

 [[0.82501907 0.07317282 0.72109159 0.99858954 0.89507733]
  [0.66160792 0.73295926 0.37149319 0.23335855 0.7405161 ]
  [0.67890123 0.86729561 0.93640664 0.45413795 0.1224886 ]]]
    
[[[1.67474401 1.34385214 1.18143654 1.65733041 1.72172414]
  [1.3038035  1.9088724  1.41034944 1.84218253 1.11612205]
  [1.6405535  1.8426777  1.8843958  1.21406958 1.72561716]]

 [[1.82501907 1.07317282 1.72109159 1.99858954 1.89507733]
  [1.66160792 1.73295926 1.37149319 1.23335855 1.7405161 ]
  [1.67890123 1.86729561 1.93640664 1.45413795 1.1224886 ]]]


In [177]:
#12. Multiply a and c. Assign the result to e.

e = a*c
e

array([[[0.67474401, 0.34385214, 0.18143654, 0.65733041, 0.72172414],
        [0.3038035 , 0.9088724 , 0.41034944, 0.84218253, 0.11612205],
        [0.6405535 , 0.8426777 , 0.8843958 , 0.21406958, 0.72561716]],

       [[0.82501907, 0.07317282, 0.72109159, 0.99858954, 0.89507733],
        [0.66160792, 0.73295926, 0.37149319, 0.23335855, 0.7405161 ],
        [0.67890123, 0.86729561, 0.93640664, 0.45413795, 0.1224886 ]]])

In [178]:
#13. Does e equal to a? Why or why not?

e==a
# si porque al multiplicar por 1, da el mismo valor.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [179]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

print(d.max())
print(d.min())
print(d.mean())
d_max=d.max()
d_min=d.min()
d_mean=d.mean()

1.9985895433737975
1.0731728160128764
1.5926615433839997


In [180]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`


f= np.empty(((2,3,5)))
f

array([[[0.67474401, 0.34385214, 0.18143654, 0.65733041, 0.72172414],
        [0.3038035 , 0.9088724 , 0.41034944, 0.84218253, 0.11612205],
        [0.6405535 , 0.8426777 , 0.8843958 , 0.21406958, 0.72561716]],

       [[0.82501907, 0.07317282, 0.72109159, 0.99858954, 0.89507733],
        [0.66160792, 0.73295926, 0.37149319, 0.23335855, 0.7405161 ],
        [0.67890123, 0.86729561, 0.93640664, 0.45413795, 0.1224886 ]]])

In [181]:
""""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

"\nIf a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.\nIf a value equals to d_mean, assign 50 to the corresponding value in f.\nAssign 0 to the corresponding value(s) in f for d_min in d.\nAssign 100 to the corresponding value(s) in f for d_max in d.\nIn the end, f should have only the following values: 0, 25, 50, 75, and 100.\nNote: you don't have to use Numpy in this question.\n"

In [204]:
f_mini = np.where((d> d_min) & (d< d_mean), 25, 0)
f_mean = np.where((d >d_mean) & (d < d_max), 75, 0)
f_media = np.where(d==d_mean, 50, 0)
f_max = np.where(d==d_max, 100, 0)
f_min = np.where(d==d_min,0, 0)
#print(f_mean)
#print(f_media)
#print(f_max)
#print(f_min)



f = (f_mean + f_media + f_max + f_min + f_mini)
f


array([[[ 75,  25,  25,  75,  75],
        [ 25,  75,  25,  75,  25],
        [ 75,  75,  75,  25,  75]],

       [[ 75,   0,  75, 100,  75],
        [ 75,  75,  25,  25,  75],
        [ 75,  75,  75,  25,  25]]])

In [198]:
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])


SyntaxError: invalid syntax (26049110.py, line 2)

In [206]:
print(d)
print(f)

[[[1.67474401 1.34385214 1.18143654 1.65733041 1.72172414]
  [1.3038035  1.9088724  1.41034944 1.84218253 1.11612205]
  [1.6405535  1.8426777  1.8843958  1.21406958 1.72561716]]

 [[1.82501907 1.07317282 1.72109159 1.99858954 1.89507733]
  [1.66160792 1.73295926 1.37149319 1.23335855 1.7405161 ]
  [1.67890123 1.86729561 1.93640664 1.45413795 1.1224886 ]]]
[[[ 75  25  25  75  75]
  [ 25  75  25  75  25]
  [ 75  75  75  25  75]]

 [[ 75   0  75 100  75]
  [ 75  75  25  25  75]
  [ 75  75  75  25  25]]]


In [ ]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [216]:
g= np.empty(((2,3,5)))
g_mini = np.where((d> d_min) & (d< d_mean), "B", 0)
g_mean = np.where((d >d_mean) & (d < d_max), "D", 0)
g_media = np.where(d==d_mean, "C", 0)
g_max = np.where(d==d_max, "E", 0)
g_min = np.where(d==d_min,"A", 0)
#print(g_mean)
#print(g_media)
#print(g_max)
#print(g_min)



g = (g_mean + g_media + g_max + g_min + g_mini)



UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> None