#1. Import the NUMPY package under the name np.

In [2]:
import numpy as np

#2. Print the NUMPY version and the configuration.

In [3]:
print(np.__version__)

1.23.4


In [4]:
print(np.show_config())

openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFI

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
#. Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
a=np.random.random((2,3,5))


#4. Print a.

In [8]:
print(a)

[[[0.56670613 0.85403163 0.5963354  0.33845523 0.03312776]
  [0.70712218 0.75701556 0.92560956 0.90090756 0.2933248 ]
  [0.59257783 0.57377546 0.75267565 0.07880332 0.64061524]]

 [[0.0542608  0.67297658 0.19531453 0.92836733 0.89606991]
  [0.87440093 0.6471911  0.85869324 0.60769556 0.37078036]
  [0.3027999  0.86576412 0.39618058 0.50477258 0.514924  ]]]


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [13]:
b=np.ones((5,2,3))

#6. Print b.

In [14]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#7. Do a and b have the same size? How do you prove that in Python code?

In [19]:
print("Size of a:",a.size)
print("Size of b:",b.size)

Size of a: 30
Size of b: 30


#8. Are you able to add a and b? Why or why not?

In [21]:
a+b

#ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 


#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [39]:
c=np.transpose(b,(1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [41]:
d=a+c

# Tienen las mismas dimensiones

print(d)

[[[1.56670613 1.85403163 1.5963354  1.33845523 1.03312776]
  [1.70712218 1.75701556 1.92560956 1.90090756 1.2933248 ]
  [1.59257783 1.57377546 1.75267565 1.07880332 1.64061524]]

 [[1.0542608  1.67297658 1.19531453 1.92836733 1.89606991]
  [1.87440093 1.6471911  1.85869324 1.60769556 1.37078036]
  [1.3027999  1.86576412 1.39618058 1.50477258 1.514924  ]]]


#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [45]:
print(a)
print("")
print(d)

# La diferencia entre ambos es b, es decir, un valor de una unidad

[[[0.56670613 0.85403163 0.5963354  0.33845523 0.03312776]
  [0.70712218 0.75701556 0.92560956 0.90090756 0.2933248 ]
  [0.59257783 0.57377546 0.75267565 0.07880332 0.64061524]]

 [[0.0542608  0.67297658 0.19531453 0.92836733 0.89606991]
  [0.87440093 0.6471911  0.85869324 0.60769556 0.37078036]
  [0.3027999  0.86576412 0.39618058 0.50477258 0.514924  ]]]

[[[1.56670613 1.85403163 1.5963354  1.33845523 1.03312776]
  [1.70712218 1.75701556 1.92560956 1.90090756 1.2933248 ]
  [1.59257783 1.57377546 1.75267565 1.07880332 1.64061524]]

 [[1.0542608  1.67297658 1.19531453 1.92836733 1.89606991]
  [1.87440093 1.6471911  1.85869324 1.60769556 1.37078036]
  [1.3027999  1.86576412 1.39618058 1.50477258 1.514924  ]]]


#12. Multiply a and c. Assign the result to e.

In [46]:
e=a*c

print(e)

[[[0.56670613 0.85403163 0.5963354  0.33845523 0.03312776]
  [0.70712218 0.75701556 0.92560956 0.90090756 0.2933248 ]
  [0.59257783 0.57377546 0.75267565 0.07880332 0.64061524]]

 [[0.0542608  0.67297658 0.19531453 0.92836733 0.89606991]
  [0.87440093 0.6471911  0.85869324 0.60769556 0.37078036]
  [0.3027999  0.86576412 0.39618058 0.50477258 0.514924  ]]]


#13. Does e equal to a? Why or why not?

In [47]:
e==a

# Al multiplicar por 1, la matriz es la misma

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [54]:
d_max=np.max(d)
print("Max:", d_max)
d_min=np.min(d)
print("Min:", d_min)
d_mean=np.mean(d)
print("Mean:", d_mean)

Max: 1.928367332282113
Min: 1.0331277649740813
Mean: 1.5767091611418382


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [57]:
f=np.empty((2,3,5))

print(f)

[[[0.56670613 0.85403163 0.5963354  0.33845523 0.03312776]
  [0.70712218 0.75701556 0.92560956 0.90090756 0.2933248 ]
  [0.59257783 0.57377546 0.75267565 0.07880332 0.64061524]]

 [[0.0542608  0.67297658 0.19531453 0.92836733 0.89606991]
  [0.87440093 0.6471911  0.85869324 0.60769556 0.37078036]
  [0.3027999  0.86576412 0.39618058 0.50477258 0.514924  ]]]


"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [69]:
fmax=np.where(d==d_max, 100, 0)
fmin=np.where(d==d_min, 0, 0)
fmean=np.where(d==d_mean,50,0)
f25=np.where((d>d_min) & (d<d_mean), 25,0)
f75=np.where((d>d_mean) & (d<d_max), 75,0)


f=fmax+fmin+fmean+f25+f75

print(f)

[[[ 25  75  75  25   0]
  [ 75  75  75  75  25]
  [ 75  25  75  25  75]]

 [[ 25  75  25 100  75]
  [ 75  75  75  75  25]
  [ 25  75  25  25  25]]]


"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [71]:
print(d)
print("")
print(f)

[[[1.56670613 1.85403163 1.5963354  1.33845523 1.03312776]
  [1.70712218 1.75701556 1.92560956 1.90090756 1.2933248 ]
  [1.59257783 1.57377546 1.75267565 1.07880332 1.64061524]]

 [[1.0542608  1.67297658 1.19531453 1.92836733 1.89606991]
  [1.87440093 1.6471911  1.85869324 1.60769556 1.37078036]
  [1.3027999  1.86576412 1.39618058 1.50477258 1.514924  ]]]

[[[ 25  75  75  25   0]
  [ 75  75  75  75  25]
  [ 75  25  75  25  75]]

 [[ 25  75  25 100  75]
  [ 75  75  75  75  25]
  [ 25  75  25  25  25]]]


"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

In [87]:
gmax=np.where(d==d_max, "E",None)
gmin=np.where(d==d_min, "A",None)
gmean=np.where(d==d_mean,"C",nan)
g25=np.where((d>d_min) & (d<d_mean), "B",None)
g75=np.where((d>d_mean) & (d<d_max), "D",None)


g=gmax+gmin+gmean+g25+g75

print(g)

NameError: name 'nan' is not defined