In [1]:
import numpy as np

In [2]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/arturo/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/arturo/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/arturo/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/arturo/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/arturo/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/arturo/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/arturo/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/arturo/opt/anaconda3/include']
Supported SIMD extensions in this NumPy install:
    base

In [3]:
a=np.random.random((2,3,5))

In [4]:
a

array([[[0.01422808, 0.71647336, 0.37368544, 0.82352738, 0.81009146],
        [0.09234917, 0.60192571, 0.04974171, 0.24434547, 0.99230726],
        [0.5109829 , 0.22395272, 0.60431254, 0.66565325, 0.5625438 ]],

       [[0.05925528, 0.5807624 , 0.02983751, 0.15873564, 0.66784761],
        [0.35962397, 0.71703187, 0.6722439 , 0.53208209, 0.80965737],
        [0.22911896, 0.5102746 , 0.26919396, 0.56192199, 0.20572996]]])

In [5]:
g=np.random.randint(0,1000,(2,3,5))

In [6]:
print(g)

[[[248  29  83 880 197]
  [ 86  27 619 217 409]
  [138 666 759 881 163]]

 [[ 43 725 787  30 954]
  [287 300 114 436 325]
  [646 823 399 994 252]]]


In [7]:
z=np.random.rand(2,3,5)

In [8]:
z

array([[[0.84086542, 0.34428663, 0.57647195, 0.08581835, 0.14983343],
        [0.10917748, 0.08178305, 0.66664461, 0.6053688 , 0.75861908],
        [0.42198451, 0.86695675, 0.709721  , 0.57111708, 0.33065623]],

       [[0.3845357 , 0.42861308, 0.86177736, 0.26560218, 0.72320431],
        [0.60268819, 0.22639023, 0.6536218 , 0.28698668, 0.1313773 ],
        [0.89728604, 0.94153415, 0.8366506 , 0.89559744, 0.02575064]]])

In [9]:
b=np.ones((5,2,3))

In [10]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
b.size

30

In [12]:
a.size

30

In [13]:
#8) no, not the same shape

In [14]:
c=b.reshape(2,3,5)

In [15]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [16]:
d=a+c
d

array([[[1.01422808, 1.71647336, 1.37368544, 1.82352738, 1.81009146],
        [1.09234917, 1.60192571, 1.04974171, 1.24434547, 1.99230726],
        [1.5109829 , 1.22395272, 1.60431254, 1.66565325, 1.5625438 ]],

       [[1.05925528, 1.5807624 , 1.02983751, 1.15873564, 1.66784761],
        [1.35962397, 1.71703187, 1.6722439 , 1.53208209, 1.80965737],
        [1.22911896, 1.5102746 , 1.26919396, 1.56192199, 1.20572996]]])

In [17]:
#11) a and c have the same shape now (2,3,5)

In [18]:
e=np.multiply(a,c)
e

array([[[0.01422808, 0.71647336, 0.37368544, 0.82352738, 0.81009146],
        [0.09234917, 0.60192571, 0.04974171, 0.24434547, 0.99230726],
        [0.5109829 , 0.22395272, 0.60431254, 0.66565325, 0.5625438 ]],

       [[0.05925528, 0.5807624 , 0.02983751, 0.15873564, 0.66784761],
        [0.35962397, 0.71703187, 0.6722439 , 0.53208209, 0.80965737],
        [0.22911896, 0.5102746 , 0.26919396, 0.56192199, 0.20572996]]])

In [19]:
#13) e equals to a because e is just a reshaped b that was multiply with a and only contains 1s : 1*a=a

In [20]:
#d_max", "d_min", and "d_mean"

In [21]:
d

array([[[1.01422808, 1.71647336, 1.37368544, 1.82352738, 1.81009146],
        [1.09234917, 1.60192571, 1.04974171, 1.24434547, 1.99230726],
        [1.5109829 , 1.22395272, 1.60431254, 1.66565325, 1.5625438 ]],

       [[1.05925528, 1.5807624 , 1.02983751, 1.15873564, 1.66784761],
        [1.35962397, 1.71703187, 1.6722439 , 1.53208209, 1.80965737],
        [1.22911896, 1.5102746 , 1.26919396, 1.56192199, 1.20572996]]])

In [22]:
d_max=d.max()
d_max

1.9923072618330298

In [23]:
d_min=d.min()
d_min

1.0142280807027393

In [24]:
d_mean=d.mean()
d_mean

1.4549812454282651

In [25]:
f=np.empty((2,3,5))
f

array([[[1.01422808, 1.71647336, 1.37368544, 1.82352738, 1.81009146],
        [1.09234917, 1.60192571, 1.04974171, 1.24434547, 1.99230726],
        [1.5109829 , 1.22395272, 1.60431254, 1.66565325, 1.5625438 ]],

       [[1.05925528, 1.5807624 , 1.02983751, 1.15873564, 1.66784761],
        [1.35962397, 1.71703187, 1.6722439 , 1.53208209, 1.80965737],
        [1.22911896, 1.5102746 , 1.26919396, 1.56192199, 1.20572996]]])

In [26]:
d

array([[[1.01422808, 1.71647336, 1.37368544, 1.82352738, 1.81009146],
        [1.09234917, 1.60192571, 1.04974171, 1.24434547, 1.99230726],
        [1.5109829 , 1.22395272, 1.60431254, 1.66565325, 1.5625438 ]],

       [[1.05925528, 1.5807624 , 1.02983751, 1.15873564, 1.66784761],
        [1.35962397, 1.71703187, 1.6722439 , 1.53208209, 1.80965737],
        [1.22911896, 1.5102746 , 1.26919396, 1.56192199, 1.20572996]]])

In [27]:
print(d_min)
print(d_mean)

1.0142280807027393
1.4549812454282651


In [28]:
conditions = [d == d_min, (d > d_min) & (d < d_mean),d == d_mean, (d>d_mean) & (d<d_max), d == d_max]
choices = [0, 25, 50, 75,100]
f = np.select(conditions,choices)

In [29]:
f

array([[[  0,  75,  25,  75,  75],
        [ 25,  75,  25,  25, 100],
        [ 75,  25,  75,  75,  75]],

       [[ 25,  75,  25,  25,  75],
        [ 25,  75,  75,  75,  75],
        [ 25,  75,  25,  75,  25]]])

In [30]:
conditions = [d == d_min, (d > d_min) & (d < d_mean),d == d_mean, (d>d_mean) & (d<d_max), d == d_max]
choices = ['A', 'B', 'C', 'D','E']
g = np.select(conditions,choices)

In [31]:
g

array([[['A', 'D', 'B', 'D', 'D'],
        ['B', 'D', 'B', 'B', 'E'],
        ['D', 'B', 'D', 'D', 'D']],

       [['B', 'D', 'B', 'B', 'D'],
        ['B', 'D', 'D', 'D', 'D'],
        ['B', 'D', 'B', 'D', 'B']]], dtype='<U3')