## 1. Import the NUMPY package under the name np.

In [1]:

import numpy as np

## 2. Print the NUMPY version and the configuration.

In [2]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

## 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [9]:
a=np.random.random((2, 3, 5))

a2=np.random.rand(2, 3, 5)

a3=np.random.randint(1,size=(2, 3, 5))

## 4. Print a.

In [11]:
a

array([[[0.48624538, 0.03940292, 0.21577047, 0.97375839, 0.60521012],
        [0.62321788, 0.86913254, 0.51125656, 0.42774325, 0.84186588],
        [0.82083582, 0.64326759, 0.53062658, 0.61940298, 0.46976695]],

       [[0.97852872, 0.39090861, 0.75554055, 0.06601846, 0.10856371],
        [0.52425879, 0.72024901, 0.39246395, 0.28832771, 0.05925264],
        [0.6726172 , 0.43717394, 0.60205026, 0.531443  , 0.05918172]]])


## 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
Assign the array to variable "b"

In [21]:
b=np.random.randint(1,2,size=(5, 2, 3))
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [23]:
b=np.full((5,2,3),1)
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

## 6.Print b.

In [24]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

## 7. Do a and b have the same size? How do you prove that in Python code?

In [31]:
print( a.shape)
print( b.shape)
a.shape == b.shape


(2, 3, 5)
(5, 2, 3)


False

## 8. Are you able to add a and b? Why or why not?

In [ ]:
#No, ya que las dimensiones son distintas

## 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [45]:
c=b.reshape(5,3,2).T

c


array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

## 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [48]:
d=np.array(a) + np.array(c)
d
#Porque ahora ambas matrices tienen la misma dimensión

array([[[1.48624538, 1.03940292, 1.21577047, 1.97375839, 1.60521012],
        [1.62321788, 1.86913254, 1.51125656, 1.42774325, 1.84186588],
        [1.82083582, 1.64326759, 1.53062658, 1.61940298, 1.46976695]],

       [[1.97852872, 1.39090861, 1.75554055, 1.06601846, 1.10856371],
        [1.52425879, 1.72024901, 1.39246395, 1.28832771, 1.05925264],
        [1.6726172 , 1.43717394, 1.60205026, 1.531443  , 1.05918172]]])

## 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [54]:
print(a)

print(d)

[[[0.48624538 0.03940292 0.21577047 0.97375839 0.60521012]
  [0.62321788 0.86913254 0.51125656 0.42774325 0.84186588]
  [0.82083582 0.64326759 0.53062658 0.61940298 0.46976695]]

 [[0.97852872 0.39090861 0.75554055 0.06601846 0.10856371]
  [0.52425879 0.72024901 0.39246395 0.28832771 0.05925264]
  [0.6726172  0.43717394 0.60205026 0.531443   0.05918172]]]
[[[1.48624538 1.03940292 1.21577047 1.97375839 1.60521012]
  [1.62321788 1.86913254 1.51125656 1.42774325 1.84186588]
  [1.82083582 1.64326759 1.53062658 1.61940298 1.46976695]]

 [[1.97852872 1.39090861 1.75554055 1.06601846 1.10856371]
  [1.52425879 1.72024901 1.39246395 1.28832771 1.05925264]
  [1.6726172  1.43717394 1.60205026 1.531443   1.05918172]]]


## 12. Multiply a and c. Assign the result to e.

In [55]:
e=np.array(a) * np.array(c)
e

array([[[0.48624538, 0.03940292, 0.21577047, 0.97375839, 0.60521012],
        [0.62321788, 0.86913254, 0.51125656, 0.42774325, 0.84186588],
        [0.82083582, 0.64326759, 0.53062658, 0.61940298, 0.46976695]],

       [[0.97852872, 0.39090861, 0.75554055, 0.06601846, 0.10856371],
        [0.52425879, 0.72024901, 0.39246395, 0.28832771, 0.05925264],
        [0.6726172 , 0.43717394, 0.60205026, 0.531443  , 0.05918172]]])

## 13. Does e equal to a? Why or why not?

In [56]:
np.array_equal(e,a)
#Porque e= a*c, siendo todos los valores de c 1

True

## 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [78]:
d_mean=d.mean() 
d_mean

1.508802719650714

In [79]:
d_max=d.max()
d_max

1.9785287229375959

In [80]:
d_min=d.min()
d_min

1.0394029173591828

## 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [81]:
f=np.empty([2,3,5])
f

array([[[0.48624538, 0.03940292, 0.21577047, 0.97375839, 0.60521012],
        [0.62321788, 0.86913254, 0.51125656, 0.42774325, 0.84186588],
        [0.82083582, 0.64326759, 0.53062658, 0.61940298, 0.46976695]],

       [[0.97852872, 0.39090861, 0.75554055, 0.06601846, 0.10856371],
        [0.52425879, 0.72024901, 0.39246395, 0.28832771, 0.05925264],
        [0.6726172 , 0.43717394, 0.60205026, 0.531443  , 0.05918172]]])

## 16. Populate the values in f. 
#### For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#### If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#### If a value equals to d_mean, assign 50 to the corresponding value in f.
#### Assign 0 to the corresponding value(s) in f for d_min in d.
#### Assign 100 to the corresponding value(s) in f for d_max in d.
#### In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#### Note: you don't have to use Numpy in this question.

In [102]:
f=np.where((d>d_min) & (d<d_mean),25,np.where((d>d_mean) & (d<d_max),75,np.where((d==d_mean),50,np.where((d==d_max),100,0))))

In [103]:
f

array([[[ 25,   0,  25,  75,  75],
        [ 75,  75,  75,  25,  75],
        [ 75,  75,  75,  75,  25]],

       [[100,  25,  75,  25,  25],
        [ 75,  75,  25,  25,  25],
        [ 75,  25,  75,  75,  25]]])

In [113]:
conditions=[(d>d_min) & (d<d_mean),(d>d_mean) & (d<d_max),(d==d_mean),(d==d_max),(d==d_min)]
choices=[25,75,50,100,0]

f=np.select(conditions,choices)
f

array([[[ 25,   0,  25,  75,  75],
        [ 75,  75,  75,  25,  75],
        [ 75,  75,  75,  75,  25]],

       [[100,  25,  75,  25,  25],
        [ 75,  75,  25,  25,  25],
        [ 75,  25,  75,  75,  25]]])

##  17. Print d and f. Do you have your expected f?
 For instance, if your d is:
 array
 
     ([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

 Your f should be:
 array
 
     ([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [114]:
print(d)
print(f)

[[[1.48624538 1.03940292 1.21577047 1.97375839 1.60521012]
  [1.62321788 1.86913254 1.51125656 1.42774325 1.84186588]
  [1.82083582 1.64326759 1.53062658 1.61940298 1.46976695]]

 [[1.97852872 1.39090861 1.75554055 1.06601846 1.10856371]
  [1.52425879 1.72024901 1.39246395 1.28832771 1.05925264]
  [1.6726172  1.43717394 1.60205026 1.531443   1.05918172]]]
[[[ 25   0  25  75  75]
  [ 75  75  75  25  75]
  [ 75  75  75  75  25]]

 [[100  25  75  25  25]
  [ 75  75  25  25  25]
  [ 75  25  75  75  25]]]


## 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array

    ([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [117]:
conditions=[(d>d_min) & (d<d_mean),(d>d_mean) & (d<d_max),(d==d_mean),(d==d_max),(d==d_min)]
choices=['A','B','C','D','E']

g=np.select(conditions,choices)
print(g)

[[['A' 'E' 'A' 'B' 'B']
  ['B' 'B' 'B' 'A' 'B']
  ['B' 'B' 'B' 'B' 'A']]

 [['D' 'A' 'B' 'A' 'A']
  ['B' 'B' 'A' 'A' 'A']
  ['B' 'A' 'B' 'B' 'A']]]
