In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np


In [2]:

#2. Print the NUMPY version and the configuration.

print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512C

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


a = np.random.random((2, 3, 5))

print(a)

[[[0.15712565 0.73803412 0.79971014 0.66279136 0.78477209]
  [0.68453216 0.59708328 0.00678844 0.35049756 0.04666725]
  [0.14246155 0.09701195 0.5826466  0.72310701 0.96742758]]

 [[0.194431   0.8409702  0.82843606 0.4355402  0.6605147 ]
  [0.94757651 0.745454   0.64664133 0.81187893 0.66018392]
  [0.40897174 0.54625329 0.72472151 0.52614716 0.38257053]]]


In [5]:
a2 = np.random.randint(0, 100, size=(2,3,5))
print(a2)

[[[25 64 50 21 27]
  [76 31 24 63 25]
  [96 24 98 38 86]]

 [[ 5 70 55 85 83]
  [63 56 81 76 94]
  [77 83 46 38  6]]]


In [6]:
a2 = np.random.rand_sample(size=(2,3,5))
print(a2)

AttributeError: module 'numpy.random' has no attribute 'rand_sample'

In [7]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

#6. Print b.
b = np.ones((5,2,3), dtype=int)
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [9]:
#7. Do a and b have the same size? How do you prove that in Python code?

a.size == b.size

True

In [10]:
#8. Are you able to add a and b? Why or why not?

np.add(a, b)

# it is not possible becuase they don´t have the same dimenssion

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [14]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.reshape(2,3,5)
c.shape

(2, 3, 5)

In [18]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = np.add(a, c)

print(d)

# because now they have the same dimenssion

[[[1.15712565 1.73803412 1.79971014 1.66279136 1.78477209]
  [1.68453216 1.59708328 1.00678844 1.35049756 1.04666725]
  [1.14246155 1.09701195 1.5826466  1.72310701 1.96742758]]

 [[1.194431   1.8409702  1.82843606 1.4355402  1.6605147 ]
  [1.94757651 1.745454   1.64664133 1.81187893 1.66018392]
  [1.40897174 1.54625329 1.72472151 1.52614716 1.38257053]]]


In [19]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print(d)

# the values of d are the results of the sum the values of a plus 1

[[[0.15712565 0.73803412 0.79971014 0.66279136 0.78477209]
  [0.68453216 0.59708328 0.00678844 0.35049756 0.04666725]
  [0.14246155 0.09701195 0.5826466  0.72310701 0.96742758]]

 [[0.194431   0.8409702  0.82843606 0.4355402  0.6605147 ]
  [0.94757651 0.745454   0.64664133 0.81187893 0.66018392]
  [0.40897174 0.54625329 0.72472151 0.52614716 0.38257053]]]
[[[1.15712565 1.73803412 1.79971014 1.66279136 1.78477209]
  [1.68453216 1.59708328 1.00678844 1.35049756 1.04666725]
  [1.14246155 1.09701195 1.5826466  1.72310701 1.96742758]]

 [[1.194431   1.8409702  1.82843606 1.4355402  1.6605147 ]
  [1.94757651 1.745454   1.64664133 1.81187893 1.66018392]
  [1.40897174 1.54625329 1.72472151 1.52614716 1.38257053]]]


In [21]:
#12. Multiply a and c. Assign the result to e.

e = np.multiply(a, c)

print(e)

[[[0.15712565 0.73803412 0.79971014 0.66279136 0.78477209]
  [0.68453216 0.59708328 0.00678844 0.35049756 0.04666725]
  [0.14246155 0.09701195 0.5826466  0.72310701 0.96742758]]

 [[0.194431   0.8409702  0.82843606 0.4355402  0.6605147 ]
  [0.94757651 0.745454   0.64664133 0.81187893 0.66018392]
  [0.40897174 0.54625329 0.72472151 0.52614716 0.38257053]]]


In [22]:
#13. Does e equal to a? Why or why not?

a == e

# yes because e is the multiply of a by 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [23]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max =d.max()
print(d_max)

d_min = d.min()
print(d_min)

d_mean = d.mean()
print(d_mean)



1.967427584891923
1.0067884380738428
1.5566982607603577


In [26]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty([2,3,5])

print(f)

[[[0.15712565 0.73803412 0.79971014 0.66279136 0.78477209]
  [0.68453216 0.59708328 0.00678844 0.35049756 0.04666725]
  [0.14246155 0.09701195 0.5826466  0.72310701 0.96742758]]

 [[0.194431   0.8409702  0.82843606 0.4355402  0.6605147 ]
  [0.94757651 0.745454   0.64664133 0.81187893 0.66018392]
  [0.40897174 0.54625329 0.72472151 0.52614716 0.38257053]]]


In [27]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


print(d)
    


[[[1.15712565 1.73803412 1.79971014 1.66279136 1.78477209]
  [1.68453216 1.59708328 1.00678844 1.35049756 1.04666725]
  [1.14246155 1.09701195 1.5826466  1.72310701 1.96742758]]

 [[1.194431   1.8409702  1.82843606 1.4355402  1.6605147 ]
  [1.94757651 1.745454   1.64664133 1.81187893 1.66018392]
  [1.40897174 1.54625329 1.72472151 1.52614716 1.38257053]]]


In [51]:
for i in range(2):
    for j in range(3):
        for z in range(5):
            if d[i][j][z] > d_min and d[i][j][z] < d_mean:
                f[i][j][z] = 25.
            elif d[i][j][z] < d_max and d[i][j][z] > d_mean:
                f[i][j][z] = 75.
            elif d[i][j][z] == d_mean:
                f[i][j][z] = 50.
            elif d[i][j][z] == d_min:
                f[i][j][z] = 0.
            elif d[i][j][z] == d_max:
                f[i][j][z] = 100.
                
print(f)

[[[ 25.  75.  75.  75.  75.]
  [ 75.  75.   0.  25.  25.]
  [ 25.  25.  75.  75. 100.]]

 [[ 25.  75.  75.  25.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  25.  75.  25.  25.]]]


In [28]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

1.0067884380738428

In [33]:
for i in range(2):
    for j in range(3):
        for z in range(5):
            if d[i][j][z] > d_min and d[i][j][z] < d_mean:
                f[i][j][z] = 'B'
            elif d[i][j][z] < d_max and d[i][j][z] > d_mean:
                f[i][j][z] = 'D'
            elif d[i][j][z] == d_mean:
                f[i][j][z] = 'C'
            elif d[i][j][z] == d_min:
                f[i][j][z] = 'A'
            elif d[i][j][z] == d_max:
                f[i][j][z] = 'E'

ValueError: could not convert string to float: 'B'

In [49]:
f[0][0][0] = str(f[0][0][0])
print(f[0][0][0])

2.0


In [50]:
type(f[0][0][0])

numpy.float64