In [12]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [13]:
#2. Print the NUMPY version and the configuration.

numpy.info

NameError: name 'numpy' is not defined

In [14]:
np.version.version

'1.21.5'

In [7]:
print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/pablo/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/pablo/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/pablo/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/pablo/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/pablo/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/pablo/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/pablo/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/pablo/Anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
   

In [ ]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [15]:
a=np.random.random((2,3,5))
a=np.random.randint(0,1, size=(2,3,5))
a=np.random.rand(2,3,5)

In [16]:
#4. Print a.

In [17]:
print(a)

[[[0.26764444 0.75731039 0.50312809 0.14170966 0.2582436 ]
  [0.0011993  0.94337058 0.41795401 0.20060885 0.15550682]
  [0.41585007 0.7898915  0.93646823 0.99617938 0.8259884 ]]

 [[0.11078988 0.41812957 0.23364994 0.84312271 0.09772485]
  [0.90642239 0.27547561 0.81603585 0.90489034 0.55290991]
  [0.68554288 0.75117948 0.76337574 0.86936034 0.89619897]]]


In [ ]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [18]:
b=np.ones((5,2,3))

In [67]:
#6. Print b.


In [19]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#7. Do a and b have the same size? How do you prove that in Python code?

In [20]:
a.size

30

In [21]:
b.size

30

In [22]:
a.size == b.size

True

In [ ]:
#8. Are you able to add a and b? Why or why not?

In [ ]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [23]:
c = b.reshape(2,3,5)


In [24]:
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [25]:

print(a.shape)
print(b.shape)
print(c.shape)

(2, 3, 5)
(5, 2, 3)
(2, 3, 5)


In [ ]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [26]:
d = np.add(a,c)

In [27]:
print(d.shape)

(2, 3, 5)


In [28]:
print(d)

[[[1.26764444 1.75731039 1.50312809 1.14170966 1.2582436 ]
  [1.0011993  1.94337058 1.41795401 1.20060885 1.15550682]
  [1.41585007 1.7898915  1.93646823 1.99617938 1.8259884 ]]

 [[1.11078988 1.41812957 1.23364994 1.84312271 1.09772485]
  [1.90642239 1.27547561 1.81603585 1.90489034 1.55290991]
  [1.68554288 1.75117948 1.76337574 1.86936034 1.89619897]]]


In [ ]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [29]:
a + 1 == d

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [ ]:
#12. Multiply a and c. Assign the result to e.


In [30]:
e = np.multiply(a,c)

In [31]:
print(e)

[[[0.26764444 0.75731039 0.50312809 0.14170966 0.2582436 ]
  [0.0011993  0.94337058 0.41795401 0.20060885 0.15550682]
  [0.41585007 0.7898915  0.93646823 0.99617938 0.8259884 ]]

 [[0.11078988 0.41812957 0.23364994 0.84312271 0.09772485]
  [0.90642239 0.27547561 0.81603585 0.90489034 0.55290991]
  [0.68554288 0.75117948 0.76337574 0.86936034 0.89619897]]]


In [32]:
print(a)
print(c)

[[[0.26764444 0.75731039 0.50312809 0.14170966 0.2582436 ]
  [0.0011993  0.94337058 0.41795401 0.20060885 0.15550682]
  [0.41585007 0.7898915  0.93646823 0.99617938 0.8259884 ]]

 [[0.11078988 0.41812957 0.23364994 0.84312271 0.09772485]
  [0.90642239 0.27547561 0.81603585 0.90489034 0.55290991]
  [0.68554288 0.75117948 0.76337574 0.86936034 0.89619897]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [ ]:
#13. Does e equal to a? Why or why not?

In [33]:
a*1 == e
# cualquier matriz multiplicada por la matriz identidad da la matriz


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [ ]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [34]:
d_max = np.max(d)

In [87]:
print(d_max)

1.9658267958890958


In [35]:
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print (d_mean)

1.0011993009150673
1.5578620595639971


In [89]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [36]:
f = np.empty((2,3,5))

In [37]:
print(f)

[[[0.26764444 0.75731039 0.50312809 0.14170966 0.2582436 ]
  [0.0011993  0.94337058 0.41795401 0.20060885 0.15550682]
  [0.41585007 0.7898915  0.93646823 0.99617938 0.8259884 ]]

 [[0.11078988 0.41812957 0.23364994 0.84312271 0.09772485]
  [0.90642239 0.27547561 0.81603585 0.90489034 0.55290991]
  [0.68554288 0.75117948 0.76337574 0.86936034 0.89619897]]]


In [ ]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [38]:
print(d)

[[[1.26764444 1.75731039 1.50312809 1.14170966 1.2582436 ]
  [1.0011993  1.94337058 1.41795401 1.20060885 1.15550682]
  [1.41585007 1.7898915  1.93646823 1.99617938 1.8259884 ]]

 [[1.11078988 1.41812957 1.23364994 1.84312271 1.09772485]
  [1.90642239 1.27547561 1.81603585 1.90489034 1.55290991]
  [1.68554288 1.75117948 1.76337574 1.86936034 1.89619897]]]


In [51]:
for matrices in d:
    
    for matriz in matrices :

        for elemento in matriz :
            if elemento > d_min and elemento < d_mean:
                elemento = 25
            elif elemento == d_mean:
                elemento = 50
            elif elemento == d_min:
                elemento == 0
            else:
                elemento == 100
                
           
    print(f)


[[[ 25.  75.  25.  25.  25.]
  [  0.  75.  25.  25.  25.]
  [ 25.  75.  75. 100.  75.]]

 [[ 25.  25.  25.  75.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  75.  75.  75.  75.]]]
[[[ 25.  75.  25.  25.  25.]
  [  0.  75.  25.  25.  25.]
  [ 25.  75.  75. 100.  75.]]

 [[ 25.  25.  25.  75.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  75.  75.  75.  75.]]]


In [52]:
print(f)

[[[ 25.  75.  25.  25.  25.]
  [  0.  75.  25.  25.  25.]
  [ 25.  75.  75. 100.  75.]]

 [[ 25.  25.  25.  75.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  75.  75.  75.  75.]]]


In [ ]:
for matriz in range (2):
    for vector in range (3):
        for elemento in range(5):
            if d[matriz][vector][elemento] > d_min and d[matriz][vector][elemento] < d_mean:
                f[matriz][vector][elemento]=25
            elif d[matriz][vector][elemento]>d_mean and d[matriz][vector][elemento] <d_max:
                f[matriz][vector][elemento]=75
            elif d[matriz][vector][elemento]==d_mean:
                f[matriz][vector][elemento]=50
            elif d[matriz][vector][elemento]==d_min:
                f[matriz][vector][elemento]=0
            elif d[matriz][vector][elemento]==d_max:
                f[matriz][vector][elemento]=100

In [53]:
print(f)

[[[ 25.  75.  25.  25.  25.]
  [  0.  75.  25.  25.  25.]
  [ 25.  75.  75. 100.  75.]]

 [[ 25.  25.  25.  75.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  75.  75.  75.  75.]]]


In [ ]:
#17. Print d and f. Do you have your expected f?

In [54]:
print(d)
print(f)

[[[1.26764444 1.75731039 1.50312809 1.14170966 1.2582436 ]
  [1.0011993  1.94337058 1.41795401 1.20060885 1.15550682]
  [1.41585007 1.7898915  1.93646823 1.99617938 1.8259884 ]]

 [[1.11078988 1.41812957 1.23364994 1.84312271 1.09772485]
  [1.90642239 1.27547561 1.81603585 1.90489034 1.55290991]
  [1.68554288 1.75117948 1.76337574 1.86936034 1.89619897]]]
[[[ 25.  75.  25.  25.  25.]
  [  0.  75.  25.  25.  25.]
  [ 25.  75.  75. 100.  75.]]

 [[ 25.  25.  25.  75.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  75.  75.  75.  75.]]]
