1. Import the NUMPY package under the name np.

In [2]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


2. Print the NUMPY version and the configuration.


In [3]:
print(np.__version__)

1.23.4


3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a".
  Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [28]:
a = np.random.random((2, 3, 5))

a


array([[[0.13300671, 0.48448106, 0.05773567, 0.97937884, 0.18050873],
        [0.38617679, 0.70113516, 0.93314147, 0.47305315, 0.38647025],
        [0.01402953, 0.16013161, 0.6109006 , 0.21569038, 0.66236013]],

       [[0.29682402, 0.11773856, 0.28335298, 0.54543024, 0.58587531],
        [0.13603175, 0.41568104, 0.51881198, 0.408297  , 0.81020442],
        [0.36707814, 0.60221701, 0.67857571, 0.38424714, 0.67737711]]])

In [29]:
a = np.random.randint(10, size=(2, 3, 5))

a

array([[[1, 2, 2, 2, 8],
        [9, 2, 1, 2, 6],
        [4, 2, 9, 9, 4]],

       [[4, 9, 5, 9, 7],
        [1, 2, 6, 1, 2],
        [4, 6, 4, 4, 3]]])

4. Print a.

In [69]:
a = np.random.rand(2,3,5)

a

array([[[0.27852898, 0.23914135, 0.38814177, 0.66868915, 0.67083113],
        [0.75120949, 0.89990666, 0.16425217, 0.65645605, 0.67493426],
        [0.20268174, 0.21959583, 0.69746143, 0.66479246, 0.22046492]],

       [[0.72157026, 0.46174032, 0.84087561, 0.21086081, 0.40427404],
        [0.53819467, 0.3191658 , 0.73156389, 0.59262289, 0.75918775],
        [0.53793129, 0.77435619, 0.3354309 , 0.77424488, 0.7764258 ]]])

In [76]:
print(a)

[[[0.27852898 0.23914135 0.38814177 0.66868915 0.67083113]
  [0.75120949 0.89990666 0.16425217 0.65645605 0.67493426]
  [0.20268174 0.21959583 0.69746143 0.66479246 0.22046492]]

 [[0.72157026 0.46174032 0.84087561 0.21086081 0.40427404]
  [0.53819467 0.3191658  0.73156389 0.59262289 0.75918775]
  [0.53793129 0.77435619 0.3354309  0.77424488 0.7764258 ]]]


5. Create a 5x2x3 3-dimensional array with all values equaling 1.
Assign the array to variable "b"

In [39]:
b = np.ones((5,3,2), dtype=int)

b

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

6. Print b.

In [27]:
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


7. Do a and b have the same size? How do you prove that in Python code?

In [32]:
a.size == b.size  #Tienen el mismo numero de elementos, pero no la misma forma...

True

In [37]:
print(a.shape)
print(b.shape)
test = []
test1 = []
test2 = []
print(a.shape == b.s)

(2, 3, 5)
(5, 3, 2)


AttributeError: 'numpy.ndarray' object has no attribute 's'

8. Are you able to add a and b? Why or why not?

In [45]:
test = a + b  #It is nor possible, as to be able to add one matrix to another one the have to have the same shape!!!




ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [46]:
c = b.T

c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [70]:
d = a + c



#It works because they have the same shape.

print('\n'+str(a.shape) + '==' + str(c.shape))

print('\n', a.shape , '==' , c.shape)


(2, 3, 5)==(2, 3, 5)

 (2, 3, 5) == (2, 3, 5)


11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [110]:
print('a =',a)
print('\n')
print('d = ',d)

a = [[[0.27852898 0.23914135 0.38814177 0.66868915 0.67083113]
  [0.75120949 0.89990666 0.16425217 0.65645605 0.67493426]
  [0.20268174 0.21959583 0.69746143 0.66479246 0.22046492]]

 [[0.72157026 0.46174032 0.84087561 0.21086081 0.40427404]
  [0.53819467 0.3191658  0.73156389 0.59262289 0.75918775]
  [0.53793129 0.77435619 0.3354309  0.77424488 0.7764258 ]]]


d =  [[[1.27852898 1.23914135 1.38814177 1.66868915 1.67083113]
  [1.75120949 1.89990666 1.16425217 1.65645605 1.67493426]
  [1.20268174 1.21959583 1.69746143 1.66479246 1.22046492]]

 [[1.72157026 1.46174032 1.84087561 1.21086081 1.40427404]
  [1.53819467 1.3191658  1.73156389 1.59262289 1.75918775]
  [1.53793129 1.77435619 1.3354309  1.77424488 1.7764258 ]]]


12. Multiply a and c. Assign the result to e.

In [85]:
e = a * c

print(e.shape)
print('\n')
print(e)
print('\n')

e = np.multiply(a, c)

print(e.shape)
print('\n')
print(e)
print('\n')

#e = np.dot(a,b) #metodo no ejecutable

# print(e.shape)
#print('\n')
#print(e)
#print('\n')

#e = np.matmul(a,c) #metodo no ejecutable

#print(e.shape)
#print('\n')
#print(e)
#print('\n')

(2, 3, 5)


[[[0.27852898 0.23914135 0.38814177 0.66868915 0.67083113]
  [0.75120949 0.89990666 0.16425217 0.65645605 0.67493426]
  [0.20268174 0.21959583 0.69746143 0.66479246 0.22046492]]

 [[0.72157026 0.46174032 0.84087561 0.21086081 0.40427404]
  [0.53819467 0.3191658  0.73156389 0.59262289 0.75918775]
  [0.53793129 0.77435619 0.3354309  0.77424488 0.7764258 ]]]


(2, 3, 5)


[[[0.27852898 0.23914135 0.38814177 0.66868915 0.67083113]
  [0.75120949 0.89990666 0.16425217 0.65645605 0.67493426]
  [0.20268174 0.21959583 0.69746143 0.66479246 0.22046492]]

 [[0.72157026 0.46174032 0.84087561 0.21086081 0.40427404]
  [0.53819467 0.3191658  0.73156389 0.59262289 0.75918775]
  [0.53793129 0.77435619 0.3354309  0.77424488 0.7764258 ]]]




13. Does e equal to a? Why or why not?

In [87]:

'''
Al multiplicar por los métodos que han funcionado se multiplica elemento a elemento, 
y en este caso al haber multiplicado una matriz random por una llena de 1s el resultado es la misma matriz random.

'''

np.equal(a, e) 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [143]:
print(d)

d_max = d.max()
print('\nEl máximo de la matriz d es = ', d_max)
d_min = d.min()
print('\nEl minimo de la matriz d es = ', d_min)
d_mean = d.mean()
print('\nLa media de la matriz d es = ', d_mean)



[[[1.27852898 1.23914135 1.38814177 1.66868915 1.67083113]
  [1.75120949 1.89990666 1.16425217 1.65645605 1.67493426]
  [1.20268174 1.21959583 1.69746143 1.66479246 1.22046492]]

 [[1.72157026 1.46174032 1.84087561 1.21086081 1.40427404]
  [1.53819467 1.3191658  1.73156389 1.59262289 1.75918775]
  [1.53793129 1.77435619 1.3354309  1.77424488 1.7764258 ]]]

El máximo de la matriz d es =  1.8999066578124106

El minimo de la matriz d es =  1.1642521731723365

La media de la matriz d es =  1.5391844167581177


15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [145]:
f = np.empty((2,3,5), dtype=int)

f

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [146]:
f = np.where(d==d_min, 0,f)

f = np.where((d>d_min)&(d<d_mean), 25,f)

f = np.where(d==d_mean, 50,f)

f = np.where((d<d_max)&(d>d_mean), 75,f)

f = np.where(d==d_max, 100,f)



'''
print(d)

d_max = d.max()
print('\nEl máximo de la matriz d es = ', d_max)
d_min = d.min()
print('\nEl minimo de la matriz d es = ', d_min)
d_mean = d.mean()
print('\nLa media de la matriz d es = ', d_mean)



'''

f

array([[[ 25,  25,  25,  75,  75],
        [ 75, 100,   0,  75,  75],
        [ 25,  25,  75,  75,  25]],

       [[ 75,  25,  75,  25,  25],
        [ 25,  25,  75,  75,  75],
        [ 25,  75,  25,  75,  75]]])

17. Print d and f. Do you have your expected f?
For instance, if your d is:

array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:

array([[[ 75.,  75.,  75.,  25.,  75.],[ 75.,  75.,  25.,  25.,  25.],[ 75.,  25.,  75.,  75.,  75.]],
 [[ 25.,  25.,  25.,  25., 100.],[ 75.,  75.,  75.,  75.,  75.],[ 25.,  75.,   0.,  75.,  75.]]])

In [148]:
print(d)
print('\n')

d_max = d.max()
print('\nEl máximo de la matriz d es = ', d_max)
d_min = d.min()
print('\nEl minimo de la matriz d es = ', d_min)
d_mean = d.mean()
print('\nLa media de la matriz d es = ', d_mean)
print('\n')
print(f)



[[[1.27852898 1.23914135 1.38814177 1.66868915 1.67083113]
  [1.75120949 1.89990666 1.16425217 1.65645605 1.67493426]
  [1.20268174 1.21959583 1.69746143 1.66479246 1.22046492]]

 [[1.72157026 1.46174032 1.84087561 1.21086081 1.40427404]
  [1.53819467 1.3191658  1.73156389 1.59262289 1.75918775]
  [1.53793129 1.77435619 1.3354309  1.77424488 1.7764258 ]]]



El máximo de la matriz d es =  1.8999066578124106

El minimo de la matriz d es =  1.1642521731723365

La media de la matriz d es =  1.5391844167581177


[[[ 25  25  25  75  75]
  [ 75 100   0  75  75]
  [ 25  25  75  75  25]]

 [[ 75  25  75  25  25]
  [ 25  25  75  75  75]
  [ 25  75  25  75  75]]]


18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [150]:
g = np.empty((2,3,5), dtype=int)


g = np.where(d==d_min, 'A',g)

g = np.where((d>d_min)&(d<d_mean), 'B',g)

g = np.where(d==d_mean, 'C',g)

g = np.where((d<d_max)&(d>d_mean), 'D',g)

g = np.where(d==d_max, 'E',g)

print(g)


[[['B' 'B' 'B' 'D' 'D']
  ['D' 'E' 'A' 'D' 'D']
  ['B' 'B' 'D' 'D' 'B']]

 [['D' 'B' 'D' 'B' 'B']
  ['B' 'B' 'D' 'D' 'D']
  ['B' 'D' 'B' 'D' 'D']]]
