#1. Import the NUMPY package under the name np.

In [102]:
import numpy as np

#2. Print the NUMPY version and the configuration.

In [103]:
np.version.version

'1.21.5'

In [104]:
print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/maria/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/maria/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/maria/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/maria/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/maria/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/maria/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/maria/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/maria/opt/anaconda3/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"

##Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [105]:
a=np.random.random((2,3,5))

In [106]:
a=np.random.randint(0,100,size =[2,3,5])

In [107]:
a=np.random.rand(2,3,5)

#4. Print a.

In [108]:
print(a)

[[[0.67621602 0.1498882  0.6491515  0.7250734  0.07470661]
  [0.14093865 0.47462258 0.97697514 0.90887452 0.53879369]
  [0.15175905 0.51975988 0.32821158 0.40628    0.06018764]]

 [[0.6056018  0.73069139 0.8259734  0.15239583 0.71931049]
  [0.50640354 0.37729897 0.88129367 0.99629702 0.54115321]
  [0.4783495  0.82274946 0.56831731 0.20471932 0.81734001]]]


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [109]:
b=np.ones((5,2,3))

#6. Print b.

In [110]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#7. Do a and b have the same size? How do you prove that in Python code?

In [111]:
a.size

30

In [112]:
a.shape

(2, 3, 5)

In [113]:
b.size

30

In [114]:
b.shape

(5, 2, 3)

In [115]:
a.size==b.size

True

#8. Are you able to add a and b? Why or why not?

In [116]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to variable "c".

In [117]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [118]:
print(b.T)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [119]:
a.shape

(2, 3, 5)

In [120]:
b.shape

(5, 2, 3)

In [121]:
b.T.shape

(3, 2, 5)

In [122]:
c=b.reshape(2,3,5)

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [123]:
d=np.add(a,c)

In [124]:
print(d)

[[[1.67621602 1.1498882  1.6491515  1.7250734  1.07470661]
  [1.14093865 1.47462258 1.97697514 1.90887452 1.53879369]
  [1.15175905 1.51975988 1.32821158 1.40628    1.06018764]]

 [[1.6056018  1.73069139 1.8259734  1.15239583 1.71931049]
  [1.50640354 1.37729897 1.88129367 1.99629702 1.54115321]
  [1.4783495  1.82274946 1.56831731 1.20471932 1.81734001]]]


In [125]:
print(a)

[[[0.67621602 0.1498882  0.6491515  0.7250734  0.07470661]
  [0.14093865 0.47462258 0.97697514 0.90887452 0.53879369]
  [0.15175905 0.51975988 0.32821158 0.40628    0.06018764]]

 [[0.6056018  0.73069139 0.8259734  0.15239583 0.71931049]
  [0.50640354 0.37729897 0.88129367 0.99629702 0.54115321]
  [0.4783495  0.82274946 0.56831731 0.20471932 0.81734001]]]


#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [126]:
a+1==d

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#12. Multiply a and c. Assign the result to e.

In [127]:
e=np.multiply(a,c)
print(e)

[[[0.67621602 0.1498882  0.6491515  0.7250734  0.07470661]
  [0.14093865 0.47462258 0.97697514 0.90887452 0.53879369]
  [0.15175905 0.51975988 0.32821158 0.40628    0.06018764]]

 [[0.6056018  0.73069139 0.8259734  0.15239583 0.71931049]
  [0.50640354 0.37729897 0.88129367 0.99629702 0.54115321]
  [0.4783495  0.82274946 0.56831731 0.20471932 0.81734001]]]


#13. Does e equal to a? Why or why not?

In [128]:
e==a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

La explicación es que cualquier matriz multiplicada por la matriz identidad da la misma matriz.

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [129]:
d_max=np.max(d)
d_max

1.9962970221234564

In [130]:
d_min=np.min(d)
d_min

1.060187636665178

In [131]:
d_mean=np.mean(d)
d_mean

1.533644446424122


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [132]:
f=np.empty((2,3,5))
f

array([[[0.67621602, 0.1498882 , 0.6491515 , 0.7250734 , 0.07470661],
        [0.14093865, 0.47462258, 0.97697514, 0.90887452, 0.53879369],
        [0.15175905, 0.51975988, 0.32821158, 0.40628   , 0.06018764]],

       [[0.6056018 , 0.73069139, 0.8259734 , 0.15239583, 0.71931049],
        [0.50640354, 0.37729897, 0.88129367, 0.99629702, 0.54115321],
        [0.4783495 , 0.82274946, 0.56831731, 0.20471932, 0.81734001]]])

"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""


In [133]:
print (f)

[[[0.67621602 0.1498882  0.6491515  0.7250734  0.07470661]
  [0.14093865 0.47462258 0.97697514 0.90887452 0.53879369]
  [0.15175905 0.51975988 0.32821158 0.40628    0.06018764]]

 [[0.6056018  0.73069139 0.8259734  0.15239583 0.71931049]
  [0.50640354 0.37729897 0.88129367 0.99629702 0.54115321]
  [0.4783495  0.82274946 0.56831731 0.20471932 0.81734001]]]


In [158]:
d_max=np.max(d)


d_min=np.min(d)


d_mean=np.mean(d)


for matriz in range (2):
    for vector in range (3):
        for elemento in range(5):
            if d[matriz][vector][elemento] > d_min and d[matriz][vector][elemento] < d_mean:
                f[matriz][vector][elemento]=25
            elif d[matriz][vector][elemento]>d_mean and d[matriz][vector][elemento] <d_max:
                f[matriz][vector][elemento]=75
            elif d[matriz][vector][elemento]==d_mean:
                f[matriz][vector][elemento]=50
            elif d[matriz][vector][elemento]==d_min:
                f[matriz][vector][elemento]=0
            elif d[matriz][vector][elemento]==d_max:
                f[matriz][vector][elemento]=100
                
print(f)
                

[[[ 75.  25.  75.  75.  25.]
  [ 25.  25.  75.  75.  75.]
  [ 25.  25.  25.  25.   0.]]

 [[ 75.  75.  75.  25.  75.]
  [ 25.  25.  75. 100.  75.]
  [ 25.  75.  75.  25.  75.]]]


"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


In [159]:
print('d_min:',d_min,'d_max:',d_max,'d_mean:',d_mean)

d_min: 1.060187636665178 d_max: 1.9962970221234564 d_mean: 1.533644446424122


In [160]:
print(d)

[[[1.67621602 1.1498882  1.6491515  1.7250734  1.07470661]
  [1.14093865 1.47462258 1.97697514 1.90887452 1.53879369]
  [1.15175905 1.51975988 1.32821158 1.40628    1.06018764]]

 [[1.6056018  1.73069139 1.8259734  1.15239583 1.71931049]
  [1.50640354 1.37729897 1.88129367 1.99629702 1.54115321]
  [1.4783495  1.82274946 1.56831731 1.20471932 1.81734001]]]


In [161]:
print(f)

[[[ 75.  25.  75.  75.  25.]
  [ 25.  25.  75.  75.  75.]
  [ 25.  25.  25.  25.   0.]]

 [[ 75.  75.  75.  25.  75.]
  [ 25.  25.  75. 100.  75.]
  [ 25.  75.  75.  25.  75.]]]


In [163]:
f.shape

(2, 3, 5)

Comprobado

"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

In [165]:
g=np.empty((3,2,5))
for matriz in range (2):
    for vector in range (3):
        for elemento in range(5):
            if f[matriz][vector][elemento] == 25:
                g[matriz][vector][elemento]='B'
            elif f[matriz][vector][elemento] == 75:
                g[matriz][vector][elemento]='D'
            elif f[matriz][vector][elemento]== 50:
                g[matriz][vector][elemento]='C'
            elif f[matriz][vector][elemento]== 0:
                g[matriz][vector][elemento]='A'
            elif f[matriz][vector][elemento]== 100:
                g[matriz][vector][elemento]='E'
                
print(g)

ValueError: could not convert string to float: 'D'