In [196]:
#1. Import the NUMPY package under the name np.
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [197]:
#2. Print the NUMPY version and the configuration.

np.version.version

'1.21.5'

In [198]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random(((2, 3, 5)))


In [199]:
#4. Print a.
a

array([[[0.32005519, 0.87548583, 0.76735991, 0.96999366, 0.17897405],
        [0.4423569 , 0.18066262, 0.18905955, 0.05351041, 0.79577409],
        [0.35874438, 0.83281779, 0.43913669, 0.42663659, 0.71919425]],

       [[0.02011518, 0.3896004 , 0.65378937, 0.56992004, 0.30131122],
        [0.34824153, 0.78664874, 0.55835769, 0.32196445, 0.7784099 ],
        [0.65144157, 0.27867405, 0.83591792, 0.77866132, 0.06449264]]])

In [200]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b  = np.ones(((5, 2, 3)))


In [201]:
#6. Print b.
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [202]:
#7. Do a and b have the same size? How do you prove that in Python code
a.size == b.size

True

In [203]:
# Are you able to add a and b? Why or why not?


#no porque no tienen el mismo numero de filas y clumnas

In [204]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.transpose(1,2,0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [205]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a + c

In [206]:
d

array([[[1.32005519, 1.87548583, 1.76735991, 1.96999366, 1.17897405],
        [1.4423569 , 1.18066262, 1.18905955, 1.05351041, 1.79577409],
        [1.35874438, 1.83281779, 1.43913669, 1.42663659, 1.71919425]],

       [[1.02011518, 1.3896004 , 1.65378937, 1.56992004, 1.30131122],
        [1.34824153, 1.78664874, 1.55835769, 1.32196445, 1.7784099 ],
        [1.65144157, 1.27867405, 1.83591792, 1.77866132, 1.06449264]]])

In [207]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)

[[[0.32005519 0.87548583 0.76735991 0.96999366 0.17897405]
  [0.4423569  0.18066262 0.18905955 0.05351041 0.79577409]
  [0.35874438 0.83281779 0.43913669 0.42663659 0.71919425]]

 [[0.02011518 0.3896004  0.65378937 0.56992004 0.30131122]
  [0.34824153 0.78664874 0.55835769 0.32196445 0.7784099 ]
  [0.65144157 0.27867405 0.83591792 0.77866132 0.06449264]]]


In [208]:
print(d)

[[[1.32005519 1.87548583 1.76735991 1.96999366 1.17897405]
  [1.4423569  1.18066262 1.18905955 1.05351041 1.79577409]
  [1.35874438 1.83281779 1.43913669 1.42663659 1.71919425]]

 [[1.02011518 1.3896004  1.65378937 1.56992004 1.30131122]
  [1.34824153 1.78664874 1.55835769 1.32196445 1.7784099 ]
  [1.65144157 1.27867405 1.83591792 1.77866132 1.06449264]]]


In [209]:
#Relation is the shape of the elements and the difference is the value of the elements

In [210]:
#12. Multiply a and c. Assign the result to e.

e= a*c

In [211]:
e

array([[[0.32005519, 0.87548583, 0.76735991, 0.96999366, 0.17897405],
        [0.4423569 , 0.18066262, 0.18905955, 0.05351041, 0.79577409],
        [0.35874438, 0.83281779, 0.43913669, 0.42663659, 0.71919425]],

       [[0.02011518, 0.3896004 , 0.65378937, 0.56992004, 0.30131122],
        [0.34824153, 0.78664874, 0.55835769, 0.32196445, 0.7784099 ],
        [0.65144157, 0.27867405, 0.83591792, 0.77866132, 0.06449264]]])

In [212]:
#13. Does e equal to a? Why or why not?
e == a


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [213]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d.max())
print(d.min())
print (d.mean())

1.9699936577158632
1.0201151817088214
1.4962435973908363


In [214]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [215]:
f = np.empty(((2, 3, 5)))

In [217]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
f_mini = np.where((d>d_min) & (d < d_mean), 25, 0)
f_mean = np.where((d > d_mean) & (d < d_max), 75, 0)
f_media = np.where(d==d_mean, 50, 0)
f_max = np.where(d==d_max, 100, 0)
f_min = np.where(d==d_min,0, 0)
f = (f_mean + f_media + f_max + f_min + f_mini)
f

array([[[ 25,  75,  75, 100,  25],
        [ 25,  25,  25,  25,  75],
        [ 25,  75,  25,  25,  75]],

       [[  0,  25,  75,  75,  25],
        [ 25,  75,  75,  25,  75],
        [ 75,  25,  75,  75,  25]]])

In [219]:
print (d)
print (f)

[[[1.32005519 1.87548583 1.76735991 1.96999366 1.17897405]
  [1.4423569  1.18066262 1.18905955 1.05351041 1.79577409]
  [1.35874438 1.83281779 1.43913669 1.42663659 1.71919425]]

 [[1.02011518 1.3896004  1.65378937 1.56992004 1.30131122]
  [1.34824153 1.78664874 1.55835769 1.32196445 1.7784099 ]
  [1.65144157 1.27867405 1.83591792 1.77866132 1.06449264]]]
[[[ 25  75  75 100  25]
  [ 25  25  25  25  75]
  [ 25  75  25  25  75]]

 [[  0  25  75  75  25]
  [ 25  75  75  25  75]
  [ 75  25  75  75  25]]]


In [ ]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), 
#how to use string values ("A", "B", "C", "D", and "E") to label the array elements? 
#You are expecting the result to be:

In [220]:
j = np.empty(((2, 3, 5)))
j_mini = np.where((d>d_min) & (d < d_mean), "B", 0)
j_mean = np.where((d > d_mean) & (d < d_max), "D", 0)
j_media = np.where(d==d_mean, "C", 0)
j_max = np.where(d==d_max, "E", 0)
j_min = np.where(d==d_min, "A", 0)
j = (j_mean + j_media + j_max + j_min + j_mini)
j

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> None