#1. Import the NUMPY package under the name np.

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

#2. Print the NUMPY version and the configuration.

In [3]:
print(np.__version__)

1.21.5


#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a = np.random.random((2,3,5))

In [5]:
a

array([[[0.15683663, 0.62118334, 0.98708927, 0.9501171 , 0.902272  ],
        [0.75024072, 0.66993049, 0.75732055, 0.96591213, 0.04914531],
        [0.93997344, 0.7820237 , 0.40330846, 0.92970548, 0.00812555]],

       [[0.02138261, 0.58978665, 0.09613706, 0.32395858, 0.63026228],
        [0.50158268, 0.03387051, 0.32483974, 0.94185877, 0.65449993],
        [0.23145463, 0.80905918, 0.73201   , 0.5102044 , 0.89812227]]])

 Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"


In [6]:
b = np.ones((5,2,3),dtype=int)

In [7]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#7. Do a and b have the same size? How do you prove that in Python code?


In [8]:
np.size(a) == np.size(b)

True

#8. Are you able to add a and b? Why or why not?


In [9]:
c = np.add(a) + np.add(b)

TypeError: add() takes from 2 to 3 positional arguments but 1 were given

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [10]:
c = np.reshape(b,(2,3,5))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?


In [11]:
d = a + c
d

array([[[1.15683663, 1.62118334, 1.98708927, 1.9501171 , 1.902272  ],
        [1.75024072, 1.66993049, 1.75732055, 1.96591213, 1.04914531],
        [1.93997344, 1.7820237 , 1.40330846, 1.92970548, 1.00812555]],

       [[1.02138261, 1.58978665, 1.09613706, 1.32395858, 1.63026228],
        [1.50158268, 1.03387051, 1.32483974, 1.94185877, 1.65449993],
        [1.23145463, 1.80905918, 1.73201   , 1.5102044 , 1.89812227]]])

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [12]:
print(a)
print(d)
#son diferentes porque hemos sumado a + b

[[[0.15683663 0.62118334 0.98708927 0.9501171  0.902272  ]
  [0.75024072 0.66993049 0.75732055 0.96591213 0.04914531]
  [0.93997344 0.7820237  0.40330846 0.92970548 0.00812555]]

 [[0.02138261 0.58978665 0.09613706 0.32395858 0.63026228]
  [0.50158268 0.03387051 0.32483974 0.94185877 0.65449993]
  [0.23145463 0.80905918 0.73201    0.5102044  0.89812227]]]
[[[1.15683663 1.62118334 1.98708927 1.9501171  1.902272  ]
  [1.75024072 1.66993049 1.75732055 1.96591213 1.04914531]
  [1.93997344 1.7820237  1.40330846 1.92970548 1.00812555]]

 [[1.02138261 1.58978665 1.09613706 1.32395858 1.63026228]
  [1.50158268 1.03387051 1.32483974 1.94185877 1.65449993]
  [1.23145463 1.80905918 1.73201    1.5102044  1.89812227]]]


#12. Multiply a and c. Assign the result to e.


In [13]:
e = a * c
e

array([[[0.15683663, 0.62118334, 0.98708927, 0.9501171 , 0.902272  ],
        [0.75024072, 0.66993049, 0.75732055, 0.96591213, 0.04914531],
        [0.93997344, 0.7820237 , 0.40330846, 0.92970548, 0.00812555]],

       [[0.02138261, 0.58978665, 0.09613706, 0.32395858, 0.63026228],
        [0.50158268, 0.03387051, 0.32483974, 0.94185877, 0.65449993],
        [0.23145463, 0.80905918, 0.73201   , 0.5102044 , 0.89812227]]])

#13. Does e equal to a? Why or why not?


In [14]:
np.array_equal(e,a)
#sí, porque la array a está compuesta por 1


True

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [15]:
d_max = np.max(d)
d_max

1.9870892684934949

In [16]:
d_min = np.min(d)
d_min

1.0081255482849307

In [17]:
d_mean = np.mean(d)
d_mean

1.5724071150782553

#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [18]:
f = np.empty((2,3,5))
f

array([[[0.15683663, 0.62118334, 0.98708927, 0.9501171 , 0.902272  ],
        [0.75024072, 0.66993049, 0.75732055, 0.96591213, 0.04914531],
        [0.93997344, 0.7820237 , 0.40330846, 0.92970548, 0.00812555]],

       [[0.02138261, 0.58978665, 0.09613706, 0.32395858, 0.63026228],
        [0.50158268, 0.03387051, 0.32483974, 0.94185877, 0.65449993],
        [0.23145463, 0.80905918, 0.73201   , 0.5102044 , 0.89812227]]])

"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""


In [40]:
f = np.where((d>d_min)&(d<d_mean), 
             25, 
             np.where(d == d_mean, 
                        50, 
                        np.where(d == d_min, 
                                 0, 
                                 np.where(d == d_max, 100, 75))))
 

In [41]:
f

array([[[ 25,  75, 100,  75,  75],
        [ 75,  75,  75,  75,  25],
        [ 75,  75,  25,  75,   0]],

       [[ 25,  75,  25,  25,  75],
        [ 25,  25,  25,  75,  75],
        [ 25,  75,  75,  25,  75]]])

#17. Print d and f. Do you have your expected f?


In [42]:
f

array([[[ 25,  75, 100,  75,  75],
        [ 75,  75,  75,  75,  25],
        [ 75,  75,  25,  75,   0]],

       [[ 25,  75,  25,  25,  75],
        [ 25,  25,  25,  75,  75],
        [ 25,  75,  75,  25,  75]]])

In [43]:
d

array([[[1.15683663, 1.62118334, 1.98708927, 1.9501171 , 1.902272  ],
        [1.75024072, 1.66993049, 1.75732055, 1.96591213, 1.04914531],
        [1.93997344, 1.7820237 , 1.40330846, 1.92970548, 1.00812555]],

       [[1.02138261, 1.58978665, 1.09613706, 1.32395858, 1.63026228],
        [1.50158268, 1.03387051, 1.32483974, 1.94185877, 1.65449993],
        [1.23145463, 1.80905918, 1.73201   , 1.5102044 , 1.89812227]]])